server:
  port: 9000
spring:
  application:
    name: spring-file
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/FILE
    username: root
    password: root
  sql:
    init:
      mode: never
mybatis:
  mapper-locations: classpath:mapper/*.xml